# Generated by Django 4.1.1 on 2022-10-08 00:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='published',
        ),
        migrations.AlterField(
            model_name='comments',
            name='content',
            field=models.TextField(default=1, validators=[django.core.validators.MinLengthValidator(1)]),
            preserve_default=False,
        ),
    ]
