# Generated by Django 4.1.2 on 2022-10-12 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_rename_comments_comment_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at', 'article'], 'verbose_name': 'comment'},
        ),
    ]
