# Generated by Django 4.1.2 on 2022-10-11 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='img',
            field=models.ImageField(blank=True, default='staticfiles/media/anon.jpg', null=True, upload_to='staticfiles/media/profile_pics'),
        ),
    ]
